// 由 scripts/gen-particle-assets.mjs 生成（Minecraft 1.21.11 / 26.2 客户端 jar）。
// 每个版本一条目：
//  - types：内置粒子类型全集（字节码 <clinit> 内置注册 ∪ assets/minecraft/particles/*.json
//    data-driven 类型；'type' 是 type{NBT} 复合语法前缀、非类型名，已排除）
//    → UI 表单粒子名下拉建议。
//  - frames：类型名 → 帧贴图列表（public/particles/<version>/<帧>.png，帧序与 MC 客户端
//    一致，帧动画时长按 MC 客户端惯例 1/20 s/帧）。未收录类型（block/dust/item 等按
//    方块纹理实时渲染的类型、未知名）→ undefined，渲染层回退软圆点。
export interface ParticleVersionData {
  types: string[];
  frames: Record<string, string[]>;
}

/** 游戏版本 → 粒子数据（类型全集/帧表）；未知版本 → undefined（上层用默认 '26.2'）。
 *  放在本文件（**纯数据、不依赖 three**）以便 UI 侧直接引用 —— 免得经 points.ts
 *  把 three 拉进首屏静态图（points.ts 里保留同名再导出，兼容既有调用点）。 */
export function particleVersionData(version: string): ParticleVersionData | undefined {
  return PARTICLE_DATA[version];
}

export const PARTICLE_DATA: Record<string, ParticleVersionData> = {


  "1.21.11": {
    types: [
"ambient_entity_effect",
    "angry_villager",
    "ash",
    "block",
    "block_crumble",
    "block_marker",
    "bubble",
    "bubble_column_up",
    "bubble_pop",
    "campfire_cosy_smoke",
    "campfire_signal_smoke",
    "cherry_leaves",
    "cloud",
    "composter",
    "copper_fire_flame",
    "crimson_spore",
    "crit",
    "current_down",
    "damage_indicator",
    "dolphin",
    "dragon_breath",
    "dripping_dripstone_lava",
    "dripping_dripstone_water",
    "dripping_honey",
    "dripping_lava",
    "dripping_obsidian_tear",
    "dripping_water",
    "dust",
    "dust_color_transition",
    "dust_pillar",
    "dust_plume",
    "effect",
    "egg_crack",
    "elder_guardian",
    "electric_spark",
    "enchant",
    "enchanted_hit",
    "end_rod",
    "entity_effect",
    "explosion",
    "explosion_emitter",
    "falling_dripstone_lava",
    "falling_dripstone_water",
    "falling_dust",
    "falling_honey",
    "falling_lava",
    "falling_nectar",
    "falling_obsidian_tear",
    "falling_spore_blossom",
    "falling_water",
    "firefly",
    "firework",
    "fishing",
    "flame",
    "flash",
    "glow",
    "glow_squid_ink",
    "gust",
    "gust_emitter_large",
    "gust_emitter_small",
    "happy_villager",
    "heart",
    "infested",
    "instant_effect",
    "item",
    "item_cobweb",
    "item_slime",
    "item_snowball",
    "landing_honey",
    "landing_lava",
    "landing_obsidian_tear",
    "large_smoke",
    "lava",
    "mycelium",
    "nautilus",
    "note",
    "ominous_spawning",
    "pale_oak_leaves",
    "poof",
    "portal",
    "raid_omen",
    "rain",
    "reverse_portal",
    "scrape",
    "sculk_charge",
    "sculk_charge_pop",
    "sculk_soul",
    "shriek",
    "small_flame",
    "small_gust",
    "smoke",
    "sneeze",
    "snowflake",
    "sonic_boom",
    "soul",
    "soul_fire_flame",
    "spit",
    "splash",
    "spore_blossom_air",
    "squid_ink",
    "sweep_attack",
    "tinted_leaves",
    "totem_of_undying",
    "trail",
    "trial_omen",
    "trial_spawner_detection",
    "trial_spawner_detection_ominous",
    "underwater",
    "vault_connection",
    "vibration",
    "warped_spore",
    "wax_off",
    "wax_on",
    "white_ash",
    "white_smoke",
    "witch",
    ],
    frames: {
    "ambient_entity_effect": ["effect_7", "effect_6", "effect_5", "effect_4", "effect_3", "effect_2", "effect_1", "effect_0"],
    "angry_villager": ["angry"],
    "ash": ["generic_0"],
    "bubble": ["bubble"],
    "bubble_column_up": ["bubble"],
    "bubble_pop": ["bubble_pop_0", "bubble_pop_1", "bubble_pop_2", "bubble_pop_3", "bubble_pop_4"],
    "campfire_cosy_smoke": ["big_smoke_0", "big_smoke_1", "big_smoke_2", "big_smoke_3", "big_smoke_4", "big_smoke_5", "big_smoke_6", "big_smoke_7", "big_smoke_8", "big_smoke_9", "big_smoke_10", "big_smoke_11"],
    "campfire_signal_smoke": ["big_smoke_0", "big_smoke_1", "big_smoke_2", "big_smoke_3", "big_smoke_4", "big_smoke_5", "big_smoke_6", "big_smoke_7", "big_smoke_8", "big_smoke_9", "big_smoke_10", "big_smoke_11"],
    "cherry_leaves": ["cherry_0", "cherry_1", "cherry_2", "cherry_3", "cherry_4", "cherry_5", "cherry_6", "cherry_7", "cherry_8", "cherry_9", "cherry_10", "cherry_11"],
    "cloud": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "composter": ["glint"],
    "copper_fire_flame": ["copper_fire_flame"],
    "crimson_spore": ["generic_0"],
    "crit": ["critical_hit"],
    "current_down": ["bubble"],
    "damage_indicator": ["damage"],
    "dolphin": ["generic_0"],
    "dragon_breath": ["generic_5", "generic_6", "generic_7"],
    "dripping_dripstone_lava": ["drip_hang"],
    "dripping_dripstone_water": ["drip_hang"],
    "dripping_honey": ["drip_hang"],
    "dripping_lava": ["drip_hang"],
    "dripping_obsidian_tear": ["drip_hang"],
    "dripping_water": ["drip_hang"],
    "dust": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "dust_color_transition": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "dust_plume": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "effect": ["effect_7", "effect_6", "effect_5", "effect_4", "effect_3", "effect_2", "effect_1", "effect_0"],
    "egg_crack": ["glint"],
    "electric_spark": ["glow"],
    "enchant": ["sga_a", "sga_b", "sga_c", "sga_d", "sga_e", "sga_f", "sga_g", "sga_h", "sga_i", "sga_j", "sga_k", "sga_l", "sga_m", "sga_n", "sga_o", "sga_p", "sga_q", "sga_r", "sga_s", "sga_t", "sga_u", "sga_v", "sga_w", "sga_x", "sga_y", "sga_z"],
    "enchanted_hit": ["enchanted_hit"],
    "end_rod": ["glitter_7", "glitter_6", "glitter_5", "glitter_4", "glitter_3", "glitter_2", "glitter_1", "glitter_0"],
    "entity_effect": ["effect_7", "effect_6", "effect_5", "effect_4", "effect_3", "effect_2", "effect_1", "effect_0"],
    "explosion": ["explosion_0", "explosion_1", "explosion_2", "explosion_3", "explosion_4", "explosion_5", "explosion_6", "explosion_7", "explosion_8", "explosion_9", "explosion_10", "explosion_11", "explosion_12", "explosion_13", "explosion_14", "explosion_15"],
    "falling_dripstone_lava": ["drip_fall"],
    "falling_dripstone_water": ["drip_fall"],
    "falling_dust": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "falling_honey": ["drip_fall"],
    "falling_lava": ["drip_fall"],
    "falling_nectar": ["drip_fall"],
    "falling_obsidian_tear": ["drip_fall"],
    "falling_spore_blossom": ["drip_fall"],
    "falling_water": ["drip_fall"],
    "firefly": ["firefly"],
    "firework": ["spark_7", "spark_6", "spark_5", "spark_4", "spark_3", "spark_2", "spark_1", "spark_0"],
    "fishing": ["splash_0", "splash_1", "splash_2", "splash_3"],
    "flame": ["flame"],
    "flash": ["flash"],
    "glow": ["glow"],
    "glow_squid_ink": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "gust": ["gust_0", "gust_1", "gust_2", "gust_3", "gust_4", "gust_5", "gust_6", "gust_7", "gust_8", "gust_9", "gust_10", "gust_11"],
    "happy_villager": ["glint"],
    "heart": ["heart"],
    "infested": ["infested"],
    "instant_effect": ["spell_7", "spell_6", "spell_5", "spell_4", "spell_3", "spell_2", "spell_1", "spell_0"],
    "landing_honey": ["drip_land"],
    "landing_lava": ["drip_land"],
    "landing_obsidian_tear": ["drip_land"],
    "large_smoke": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "lava": ["lava"],
    "mycelium": ["generic_0"],
    "nautilus": ["nautilus"],
    "note": ["note"],
    "ominous_spawning": ["ominous_spawning"],
    "pale_oak_leaves": ["pale_oak_0", "pale_oak_1", "pale_oak_2", "pale_oak_3", "pale_oak_4", "pale_oak_5", "pale_oak_6", "pale_oak_7", "pale_oak_8", "pale_oak_9", "pale_oak_10", "pale_oak_11"],
    "poof": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "portal": ["generic_0", "generic_1", "generic_2", "generic_3", "generic_4", "generic_5", "generic_6", "generic_7"],
    "raid_omen": ["raid_omen"],
    "rain": ["splash_0", "splash_1", "splash_2", "splash_3"],
    "reverse_portal": ["generic_0", "generic_1", "generic_2", "generic_3", "generic_4", "generic_5", "generic_6", "generic_7"],
    "scrape": ["glow"],
    "sculk_charge": ["sculk_charge_0", "sculk_charge_1", "sculk_charge_2", "sculk_charge_3", "sculk_charge_4", "sculk_charge_5", "sculk_charge_6"],
    "sculk_charge_pop": ["sculk_charge_pop_0", "sculk_charge_pop_1", "sculk_charge_pop_2", "sculk_charge_pop_3"],
    "sculk_soul": ["sculk_soul_0", "sculk_soul_1", "sculk_soul_2", "sculk_soul_3", "sculk_soul_4", "sculk_soul_5", "sculk_soul_6", "sculk_soul_7", "sculk_soul_8", "sculk_soul_9", "sculk_soul_10"],
    "shriek": ["shriek"],
    "small_flame": ["flame"],
    "small_gust": ["small_gust_0", "small_gust_1", "small_gust_2", "small_gust_3", "small_gust_4", "small_gust_5", "small_gust_6"],
    "smoke": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "sneeze": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "snowflake": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "sonic_boom": ["sonic_boom_0", "sonic_boom_1", "sonic_boom_2", "sonic_boom_3", "sonic_boom_4", "sonic_boom_5", "sonic_boom_6", "sonic_boom_7", "sonic_boom_8", "sonic_boom_9", "sonic_boom_10", "sonic_boom_11", "sonic_boom_12", "sonic_boom_13", "sonic_boom_14", "sonic_boom_15"],
    "soul": ["soul_0", "soul_1", "soul_2", "soul_3", "soul_4", "soul_5", "soul_6", "soul_7", "soul_8", "soul_9", "soul_10"],
    "soul_fire_flame": ["soul_fire_flame"],
    "spit": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "splash": ["splash_0", "splash_1", "splash_2", "splash_3"],
    "spore_blossom_air": ["drip_fall"],
    "squid_ink": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "sweep_attack": ["sweep_0", "sweep_1", "sweep_2", "sweep_3", "sweep_4", "sweep_5", "sweep_6", "sweep_7"],
    "tinted_leaves": ["leaf_0", "leaf_1", "leaf_2", "leaf_3", "leaf_4", "leaf_5", "leaf_6", "leaf_7", "leaf_8", "leaf_9", "leaf_10", "leaf_11"],
    "totem_of_undying": ["glitter_7", "glitter_6", "glitter_5", "glitter_4", "glitter_3", "glitter_2", "glitter_1", "glitter_0"],
    "trail": ["generic_0"],
    "trial_omen": ["trial_omen"],
    "trial_spawner_detection": ["trial_spawner_detection_0", "trial_spawner_detection_1", "trial_spawner_detection_2", "trial_spawner_detection_3", "trial_spawner_detection_4"],
    "trial_spawner_detection_ominous": ["trial_spawner_detection_ominous_0", "trial_spawner_detection_ominous_1", "trial_spawner_detection_ominous_2", "trial_spawner_detection_ominous_3", "trial_spawner_detection_ominous_4"],
    "underwater": ["generic_0"],
    "vault_connection": ["vault_connection"],
    "vibration": ["vibration"],
    "warped_spore": ["generic_0"],
    "wax_off": ["glow"],
    "wax_on": ["glow"],
    "white_ash": ["generic_0"],
    "white_smoke": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "witch": ["spell_7", "spell_6", "spell_5", "spell_4", "spell_3", "spell_2", "spell_1", "spell_0"],
    },
  }, 

  "26.2": {
    types: [
"ambient_entity_effect",
    "angry_villager",
    "ash",
    "block",
    "block_crumble",
    "block_marker",
    "bubble",
    "bubble_column_up",
    "bubble_pop",
    "campfire_cosy_smoke",
    "campfire_signal_smoke",
    "cherry_leaves",
    "cloud",
    "composter",
    "copper_fire_flame",
    "crimson_spore",
    "crit",
    "current_down",
    "damage_indicator",
    "dolphin",
    "dragon_breath",
    "dripping_dripstone_lava",
    "dripping_dripstone_water",
    "dripping_honey",
    "dripping_lava",
    "dripping_obsidian_tear",
    "dripping_water",
    "dust",
    "dust_color_transition",
    "dust_pillar",
    "dust_plume",
    "effect",
    "egg_crack",
    "elder_guardian",
    "electric_spark",
    "enchant",
    "enchanted_hit",
    "end_rod",
    "entity_effect",
    "explosion",
    "explosion_emitter",
    "falling_dripstone_lava",
    "falling_dripstone_water",
    "falling_dust",
    "falling_honey",
    "falling_lava",
    "falling_nectar",
    "falling_obsidian_tear",
    "falling_spore_blossom",
    "falling_water",
    "firefly",
    "firework",
    "fishing",
    "flame",
    "flash",
    "geyser",
    "geyser_base",
    "geyser_plume",
    "geyser_poof",
    "glow",
    "glow_squid_ink",
    "gust",
    "gust_emitter_large",
    "gust_emitter_small",
    "happy_villager",
    "heart",
    "infested",
    "instant_effect",
    "item",
    "item_cobweb",
    "item_slime",
    "item_snowball",
    "landing_honey",
    "landing_lava",
    "landing_obsidian_tear",
    "large_smoke",
    "lava",
    "mycelium",
    "nautilus",
    "note",
    "noxious_gas",
    "noxious_gas_cloud",
    "ominous_spawning",
    "pale_oak_leaves",
    "pause_mob_growth",
    "poof",
    "portal",
    "raid_omen",
    "rain",
    "reset_mob_growth",
    "reverse_portal",
    "scrape",
    "sculk_charge",
    "sculk_charge_pop",
    "sculk_soul",
    "shriek",
    "small_flame",
    "small_gust",
    "smoke",
    "sneeze",
    "snowflake",
    "sonic_boom",
    "soul",
    "soul_fire_flame",
    "spit",
    "splash",
    "spore_blossom_air",
    "squid_ink",
    "sulfur_bubbles",
    "sulfur_cube_goo",
    "sweep_attack",
    "tinted_leaves",
    "totem_of_undying",
    "trail",
    "trial_omen",
    "trial_spawner_detection",
    "trial_spawner_detection_ominous",
    "underwater",
    "vault_connection",
    "vibration",
    "warped_spore",
    "wax_off",
    "wax_on",
    "white_ash",
    "white_smoke",
    "witch",
    ],
    frames: {
    "ambient_entity_effect": ["effect_7", "effect_6", "effect_5", "effect_4", "effect_3", "effect_2", "effect_1", "effect_0"],
    "angry_villager": ["angry"],
    "ash": ["generic_0"],
    "bubble": ["bubble"],
    "bubble_column_up": ["bubble"],
    "bubble_pop": ["bubble_pop_0", "bubble_pop_1", "bubble_pop_2", "bubble_pop_3", "bubble_pop_4"],
    "campfire_cosy_smoke": ["big_smoke_0", "big_smoke_1", "big_smoke_2", "big_smoke_3", "big_smoke_4", "big_smoke_5", "big_smoke_6", "big_smoke_7", "big_smoke_8", "big_smoke_9", "big_smoke_10", "big_smoke_11"],
    "campfire_signal_smoke": ["big_smoke_0", "big_smoke_1", "big_smoke_2", "big_smoke_3", "big_smoke_4", "big_smoke_5", "big_smoke_6", "big_smoke_7", "big_smoke_8", "big_smoke_9", "big_smoke_10", "big_smoke_11"],
    "cherry_leaves": ["cherry_0", "cherry_1", "cherry_2", "cherry_3", "cherry_4", "cherry_5", "cherry_6", "cherry_7", "cherry_8", "cherry_9", "cherry_10", "cherry_11"],
    "cloud": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "composter": ["glint"],
    "copper_fire_flame": ["copper_fire_flame"],
    "crimson_spore": ["generic_0"],
    "crit": ["critical_hit"],
    "current_down": ["bubble"],
    "damage_indicator": ["damage"],
    "dolphin": ["generic_0"],
    "dragon_breath": ["generic_5", "generic_6", "generic_7"],
    "dripping_dripstone_lava": ["drip_hang"],
    "dripping_dripstone_water": ["drip_hang"],
    "dripping_honey": ["drip_hang"],
    "dripping_lava": ["drip_hang"],
    "dripping_obsidian_tear": ["drip_hang"],
    "dripping_water": ["drip_hang"],
    "dust": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "dust_color_transition": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "dust_plume": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "effect": ["effect_7", "effect_6", "effect_5", "effect_4", "effect_3", "effect_2", "effect_1", "effect_0"],
    "egg_crack": ["glint"],
    "electric_spark": ["glow"],
    "enchant": ["sga_a", "sga_b", "sga_c", "sga_d", "sga_e", "sga_f", "sga_g", "sga_h", "sga_i", "sga_j", "sga_k", "sga_l", "sga_m", "sga_n", "sga_o", "sga_p", "sga_q", "sga_r", "sga_s", "sga_t", "sga_u", "sga_v", "sga_w", "sga_x", "sga_y", "sga_z"],
    "enchanted_hit": ["enchanted_hit"],
    "end_rod": ["glitter_7", "glitter_6", "glitter_5", "glitter_4", "glitter_3", "glitter_2", "glitter_1", "glitter_0"],
    "entity_effect": ["effect_7", "effect_6", "effect_5", "effect_4", "effect_3", "effect_2", "effect_1", "effect_0"],
    "explosion": ["explosion_0", "explosion_1", "explosion_2", "explosion_3", "explosion_4", "explosion_5", "explosion_6", "explosion_7", "explosion_8", "explosion_9", "explosion_10", "explosion_11", "explosion_12", "explosion_13", "explosion_14", "explosion_15"],
    "falling_dripstone_lava": ["drip_fall"],
    "falling_dripstone_water": ["drip_fall"],
    "falling_dust": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "falling_honey": ["drip_fall"],
    "falling_lava": ["drip_fall"],
    "falling_nectar": ["drip_fall"],
    "falling_obsidian_tear": ["drip_fall"],
    "falling_spore_blossom": ["drip_fall"],
    "falling_water": ["drip_fall"],
    "firefly": ["firefly"],
    "firework": ["spark_7", "spark_6", "spark_5", "spark_4", "spark_3", "spark_2", "spark_1", "spark_0"],
    "fishing": ["splash_0", "splash_1", "splash_2", "splash_3"],
    "flame": ["flame"],
    "flash": ["flash"],
    "geyser_base": ["geyser_base_01", "geyser_base_02", "geyser_base_03", "geyser_base_04", "geyser_base_05", "geyser_base_06", "geyser_base_07", "geyser_base_08"],
    "geyser_plume": ["geyser_plume_01", "geyser_plume_02", "geyser_plume_03", "geyser_plume_04", "geyser_plume_05", "geyser_plume_06", "geyser_plume_07", "geyser_plume_08"],
    "geyser_poof": ["geyser_poof_01", "geyser_poof_02", "geyser_poof_03", "geyser_poof_04", "geyser_poof_05", "geyser_poof_06", "geyser_poof_07", "geyser_poof_08"],
    "glow": ["glow"],
    "glow_squid_ink": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "gust": ["gust_0", "gust_1", "gust_2", "gust_3", "gust_4", "gust_5", "gust_6", "gust_7", "gust_8", "gust_9", "gust_10", "gust_11"],
    "happy_villager": ["glint"],
    "heart": ["heart"],
    "infested": ["infested"],
    "instant_effect": ["spell_7", "spell_6", "spell_5", "spell_4", "spell_3", "spell_2", "spell_1", "spell_0"],
    "landing_honey": ["drip_land"],
    "landing_lava": ["drip_land"],
    "landing_obsidian_tear": ["drip_land"],
    "large_smoke": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "lava": ["lava"],
    "mycelium": ["generic_0"],
    "nautilus": ["nautilus"],
    "note": ["note"],
    "noxious_gas": ["noxious_gas_01", "noxious_gas_02", "noxious_gas_03", "noxious_gas_04", "noxious_gas_05", "noxious_gas_06", "noxious_gas_07", "noxious_gas_08"],
    "ominous_spawning": ["ominous_spawning"],
    "pale_oak_leaves": ["pale_oak_0", "pale_oak_1", "pale_oak_2", "pale_oak_3", "pale_oak_4", "pale_oak_5", "pale_oak_6", "pale_oak_7", "pale_oak_8", "pale_oak_9", "pale_oak_10", "pale_oak_11"],
    "pause_mob_growth": ["glint"],
    "poof": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "portal": ["generic_0", "generic_1", "generic_2", "generic_3", "generic_4", "generic_5", "generic_6", "generic_7"],
    "raid_omen": ["raid_omen"],
    "rain": ["splash_0", "splash_1", "splash_2", "splash_3"],
    "reset_mob_growth": ["glint"],
    "reverse_portal": ["generic_0", "generic_1", "generic_2", "generic_3", "generic_4", "generic_5", "generic_6", "generic_7"],
    "scrape": ["glow"],
    "sculk_charge": ["sculk_charge_0", "sculk_charge_1", "sculk_charge_2", "sculk_charge_3", "sculk_charge_4", "sculk_charge_5", "sculk_charge_6"],
    "sculk_charge_pop": ["sculk_charge_pop_0", "sculk_charge_pop_1", "sculk_charge_pop_2", "sculk_charge_pop_3"],
    "sculk_soul": ["sculk_soul_0", "sculk_soul_1", "sculk_soul_2", "sculk_soul_3", "sculk_soul_4", "sculk_soul_5", "sculk_soul_6", "sculk_soul_7", "sculk_soul_8", "sculk_soul_9", "sculk_soul_10"],
    "shriek": ["shriek"],
    "small_flame": ["flame"],
    "small_gust": ["small_gust_0", "small_gust_1", "small_gust_2", "small_gust_3", "small_gust_4", "small_gust_5", "small_gust_6"],
    "smoke": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "sneeze": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "snowflake": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "sonic_boom": ["sonic_boom_0", "sonic_boom_1", "sonic_boom_2", "sonic_boom_3", "sonic_boom_4", "sonic_boom_5", "sonic_boom_6", "sonic_boom_7", "sonic_boom_8", "sonic_boom_9", "sonic_boom_10", "sonic_boom_11", "sonic_boom_12", "sonic_boom_13", "sonic_boom_14", "sonic_boom_15"],
    "soul": ["soul_0", "soul_1", "soul_2", "soul_3", "soul_4", "soul_5", "soul_6", "soul_7", "soul_8", "soul_9", "soul_10"],
    "soul_fire_flame": ["soul_fire_flame"],
    "spit": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "splash": ["splash_0", "splash_1", "splash_2", "splash_3"],
    "spore_blossom_air": ["drip_fall"],
    "squid_ink": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "sulfur_bubbles": ["bubble_white"],
    "sulfur_cube_goo": ["sulfur_cube_goo"],
    "sweep_attack": ["sweep_0", "sweep_1", "sweep_2", "sweep_3", "sweep_4", "sweep_5", "sweep_6", "sweep_7"],
    "tinted_leaves": ["leaf_0", "leaf_1", "leaf_2", "leaf_3", "leaf_4", "leaf_5", "leaf_6", "leaf_7", "leaf_8", "leaf_9", "leaf_10", "leaf_11"],
    "totem_of_undying": ["glitter_7", "glitter_6", "glitter_5", "glitter_4", "glitter_3", "glitter_2", "glitter_1", "glitter_0"],
    "trail": ["generic_0"],
    "trial_omen": ["trial_omen"],
    "trial_spawner_detection": ["trial_spawner_detection_0", "trial_spawner_detection_1", "trial_spawner_detection_2", "trial_spawner_detection_3", "trial_spawner_detection_4"],
    "trial_spawner_detection_ominous": ["trial_spawner_detection_ominous_0", "trial_spawner_detection_ominous_1", "trial_spawner_detection_ominous_2", "trial_spawner_detection_ominous_3", "trial_spawner_detection_ominous_4"],
    "underwater": ["generic_0"],
    "vault_connection": ["vault_connection"],
    "vibration": ["vibration"],
    "warped_spore": ["generic_0"],
    "wax_off": ["glow"],
    "wax_on": ["glow"],
    "white_ash": ["generic_0"],
    "white_smoke": ["generic_7", "generic_6", "generic_5", "generic_4", "generic_3", "generic_2", "generic_1", "generic_0"],
    "witch": ["spell_7", "spell_6", "spell_5", "spell_4", "spell_3", "spell_2", "spell_1", "spell_0"],
    },
  }, };
